set_property IOSTANDARD LVCMOS33 [get_ports *]

set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports rst]
set_property PACKAGE_PIN N5 [get_ports rx]
set_property PACKAGE_PIN T4 [get_ports tx]

set_property PACKAGE_PIN U4 [get_ports up_i]
set_property PACKAGE_PIN V1 [get_ports left_i]
set_property PACKAGE_PIN R11 [get_ports right_i]
set_property PACKAGE_PIN R15 [get_ports confirm_i]
set_property PACKAGE_PIN R17 [get_ports down_i]

set_property PACKAGE_PIN P5 [get_ports switch[7]]
set_property PACKAGE_PIN P4 [get_ports switch[6]]
set_property PACKAGE_PIN P3 [get_ports switch[5]]
set_property PACKAGE_PIN P2 [get_ports switch[4]]
set_property PACKAGE_PIN R2 [get_ports switch[3]]
set_property PACKAGE_PIN M4 [get_ports switch[2]]
set_property PACKAGE_PIN N4 [get_ports switch[1]]
set_property PACKAGE_PIN R1 [get_ports switch[0]]

set_property PACKAGE_PIN F6 [get_ports {light[7]}]
set_property PACKAGE_PIN G4 [get_ports {light[6]}]
set_property PACKAGE_PIN G3 [get_ports {light[5]}]
set_property PACKAGE_PIN J4 [get_ports {light[4]}]
set_property PACKAGE_PIN H4 [get_ports {light[3]}]
set_property PACKAGE_PIN J3 [get_ports {light[2]}]
set_property PACKAGE_PIN J2 [get_ports {light[1]}]
set_property PACKAGE_PIN K2 [get_ports {light[0]}]

set_property PACKAGE_PIN G2 [get_ports {tub_ctrl[7]}]
set_property PACKAGE_PIN C2 [get_ports {tub_ctrl[6]}]
set_property PACKAGE_PIN C1 [get_ports {tub_ctrl[5]}]
set_property PACKAGE_PIN H1 [get_ports {tub_ctrl[4]}]
set_property PACKAGE_PIN G1 [get_ports {tub_ctrl[3]}]
set_property PACKAGE_PIN F1 [get_ports {tub_ctrl[2]}]
set_property PACKAGE_PIN E1 [get_ports {tub_ctrl[1]}]
set_property PACKAGE_PIN G6 [get_ports {tub_ctrl[0]}]

set_property PACKAGE_PIN B4 [get_ports {seg_ctrl1[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_ctrl1[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_ctrl1[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_ctrl1[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_ctrl1[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_ctrl1[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_ctrl1[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_ctrl1[0]}]

set_property PACKAGE_PIN D4 [get_ports {seg_ctrl2[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_ctrl2[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_ctrl2[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_ctrl2[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_ctrl2[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_ctrl2[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_ctrl2[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_ctrl2[0]}]